--- 
phases: 
    build: 
        commands: 
            - "echo Build started on `date`"
            - "echo Building the Docker image..."
            - "docker build -t janitha000/github-microservice ."
            - "docker tag janitha000/github-microservice djanitha000/github-microservice:latest"
    post_build: 
        commands: 
            - "echo Build completed on `date`"
            - "echo Pushing the Docker image..."
    pre_build: 
        commands: 
            - "echo Logging in to Docker Hub..."
    artifacts:    
        files:
            - '**/*'
version: 0.1