GET http://localhost:3001/movies

###
GET http://localhost:3001/movies/123
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IldvRkktWHpLMUM1Z2g1YmxwY1ZmUyJ9.eyJpc3MiOiJodHRwczovL2phbml0aGEwMDAuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTE0MjU4MDA5MzM4MTY5ODA3OTQzIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMSIsImh0dHBzOi8vamFuaXRoYTAwMC5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNTg4OTAxMTQyLCJleHAiOjE1ODg5MDgzNDIsImF6cCI6IjNrMDRqekpXb0VMWWwwd2QyOUt2ZkdzNkpRdTdXNlNEIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSIsInBlcm1pc3Npb25zIjpbXX0.dnDunhcsoRyAoauJ36Xa1sNwkstODvkS1f0gP-jxws0ovsZMFQ_LZ6KoVp5t3eWKw-ftEJW3AP8I3mS6BU2DpBmU3CGlfDaqW-K9jSLr2LczWdzHiR0KK93iDMuNswtFNPK_pT9ZUegskWHE1GdPrTlp-nuWZUprjdtytc7P8ofzVaslruCGv_NRLRih6tiOTxhiU7w182qJ5n9lzHwZDg5pNV_efyHNEl5PWw1Sx5Kt2cdBVHC5mlEh6JMj0b14ddTUHYptkjfvPNVgVI5wXAB95bi9yXPWZFho3CSpA8KBSk0p8zeJQCyn--TEKvBdH-oMGG0uYrKMr-BnLL6J0A


###
GET https://nc16cp9mie.execute-api.ap-southeast-1.amazonaws.com/Dev/movies/123